### PR TITLE
feat: Add organization_role data source

### PR DESCRIPTION
**Pull request by aperigault**
Needs https://github.com/f0rkz/goawx/pull/2

### CODE REVIEW

**Comment by f0rkz** [comment]
Thank's for the Pull Request. I will review shortly.

**Comment by f0rkz** [comment]
f0rkz/goawx#2 merged and versioned at v0.6.0 please update the `go.mod` file to reflect this change.

**Review by f0rkz — CHANGES_REQUESTED** [review]
Please update `go.mod` to point to f0rkz/goawx v0.6.0

**Comment by aperigault** [comment]
Thanks for your review.
Change done.

**Comment by aperigault** [comment]
Hi @f0rkz, have you any time to terminate the review ?

**Comment by f0rkz** [comment]
Sorry about the delay on this!! Work has been keeping me busy. I will get this validated and released!

**Comment by f0rkz** [comment]
Wew lad. Finally getting back to this. Its been a weird few months. Getting back on track!

**Pull request merged**
