### PR TITLE
feat: Add setting resource

### PR DESCRIPTION
**Pull request by aperigault**
Hi,
light but fonctional generic AWX setting resource. I'm not a Go developer so it can probably be improved by professionals :-).

### CODE REVIEW

**Comment by f0rkz** [comment]
Thanks for the PR! I will review and get it merged soon!

**Comment by aperigault** [comment]
Hi, I just push a new commit with another proposal with only one `value` attribute. It is more simple but need to "stringify" the json passed.
Tell me what do you think about it ?

**Comment by f0rkz** [comment]
> Tell me what do you think about it ?

Will do! I am going to try and get this tonight. Sorry for the delay!

**Comment by aperigault** [comment]
Hi @f0rkz, have you forgot this?

**Review by f0rkz — APPROVED** [review]
Sorry for the delay. Was dealing with some stuff. This looks good!

**Pull request merged**
